---
title: "HW_template_Rmarkdown"
author: "Pedram Jahangiry"
date: ""
output:
  pdf_document: default
  word_document: default
---

\tableofcontents


\newpage

# Problems

## Question 1

### (i) 

This is my answer to section (i)

### (ii)

This is my answer to section (ii)

---------



# Computer Exercises

```{r include=FALSE}
library(wooldridge)
```

## C1 Use the data in wage1 for this exercise.

### (i) 

This is my answer to section (i)
 







# Including r output within some text 

for example I calculated the average number of cars as: 
```{r}
avg_speed <- mean(cars$speed)
avg_speed
```

from the R output above, we see that the average speed is equal to 15.4. 

Or you could directly do some in-line calculations. 
Here is the average speed: `r mean(cars$speed)`. 

We can also insert plots from R in Rmarkdown: 


```{r}
hist(wage2$wage, col="red")
```



-------------


How to write mathematical formulas in **Rmarkdown**: 

1. Writing in-line formulas using one dollar sign: $y=\beta_0 + \beta_1 x_1 + ... + \beta_k x_k + u$


2. Writing centered and stand alone formulas using 2 dollar signs: 
$$y=\beta_0 + \beta_1 x_1 + ... + \beta_k x_k + u$$
$$P(X|Y)$$

$log(salary)$

$P(X \le 6)$

$f(x)=3x^2 -2x^3$  then $0 \le x \le 1$

---------------




